services:
  thymely_postgres:
    container_name: thymely_postgres
    image: postgres:17
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  thymely:
    container_name: thymely
    image: ghcr.io/gitcroque/thymely:latest
    ports:
      - 1000:3000
      - 1001:5003
    restart: always
    depends_on:
      thymely_postgres:
        condition: service_healthy
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: thymely_postgres
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@thymely_postgres:5432/${POSTGRES_DB:-thymely}
      SECRET: ${SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      HOSTNAME: "0.0.0.0"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
    internal: true

volumes:
  pgdata:
